// Generated by scripts/generate-profile.mjs. Edit profiles/*.json or env vars instead.
export const APP_PROFILE = {
  "brand": {
    "name": "Spark Atlas",
    "desktopName": "Spark Atlas",
    "serviceName": "Open WebUI",
    "description": "Spark Atlas",
    "author": "Spark Atlas",
    "homepage": "https://openwebui.com",
    "officialWebsiteUrl": "https://spark-ai.top",
    "copyrightText": "Copyright (c) 2026 Spark Atlas. All rights reserved.",
    "creatorText": "Created by Spark Atlas",
    "packageName": "spark-atlas-desktop",
    "appId": "com.sparkatlas.desktop",
    "executableName": "spark-atlas",
    "linuxMaintainer": "openwebui.com",
    "githubOwner": "open-webui",
    "githubRepo": "desktop"
  },
  "features": {
    "allowLocalOpenWebUIInstall": false,
    "allowUserRemoteOpenWebUI": false,
    "defaultRemoteOpenWebUI": "https://chat.spark-ai.top",
    "defaultRemoteOpenWebUIName": "Spark Atlas",
    "defaultLandingMode": "remote",
    "allowRemotePasskeys": true,
    "allowRemoteDesktopBridge": true,
    "allowRemoteNativeApi": true,
    "allowRemoteLocalResources": true
  },
  "remotePermissions": {
    "allowed": [
      "media",
      "mediaKeySystem",
      "notifications",
      "clipboard-read",
      "clipboard-sanitized-write",
      "clipboard-read-write",
      "fullscreen",
      "geolocation",
      "hid",
      "serial",
      "usb",
      "pointerLock"
    ]
  },
  "auth": {
    "allowExternalAuthOriginsInWebview": true,
    "allowedAuthOrigins": []
  },
  "desktopBridge": {
    "allowedCapabilities": [
      "app.info",
      "app.openExternal",
      "app.openSettings",
      "system.platform",
      "system.selectFolder",
      "resources.openPath",
      "resources.selectFile",
      "terminal.local.info",
      "terminal.local.state",
      "terminal.local.ensure",
      "terminal.local.start",
      "terminal.local.stop",
      "terminal.local.restart",
      "terminal.local.install",
      "terminal.local.update",
      "terminal.local.uninstall",
      "terminal.local.configure"
    ]
  },
  "updates": {
    "provider": "generic",
    "owner": "open-webui",
    "repo": "desktop",
    "url": "https://chat.spark-ai.top/api/v1/configs/apps/updates/desktop/",
    "updaterCacheDirName": "spark-atlas-updater",
    "currentVersion": ""
  },
  "assets": {
    "iconDir": "/Users/cary/Desktop/Fun/Spark Atlas/icons",
    "iconPng": "light.png",
    "iconIco": "light.ico",
    "trayPng": "carved_light.png",
    "macIconScale": 0.82,
    "splashLightPng": "carved_light.png",
    "splashDarkPng": "carved_dark.png"
  }
} as const

export type AppProfile = typeof APP_PROFILE
